### ISSUE TITLE
Implement database

### ISSUE THREAD

**Issue by cprbucat2** [cprbucat2/team-feedback#4]
**Is your feature request related to a problem? Please describe.**
There is nowhere to store our data.

**Describe the solution you'd like**
Add Go server code to store data in a MySQL server on the docker network.

**Describe alternatives you've considered**
Idk single files maybe. Sqlite. But we expect production servers to be performant.
It might be better to use a nosql database like https://dgraph.io/docs/badger/ since we are storing some arbitrary length comments.

**Additional context**
Depends directly on #41 and indirectly #47.

**Comment by bobpaw** [comment]
@cprbucat2 We need to change how the database password is generated/accessed.
