### ISSUE TITLE
Add javascript to HTML form

### ISSUE THREAD

**Issue by cprbucat2** [cprbucat2/team-feedback#43]
**Is your feature request related to a problem? Please describe.**
HTML form does not validate number data, collect data, calculate averages, allow submit.

**Describe the solution you'd like**
- [x] #37 
- [x] #54
- [x] Form collection and submission (#47)

**Describe alternatives you've considered**

**Additional context**

**Comment by bobpaw** [comment]
W we did all the tasks.
